HBW-376 Add tooltip message translation for string filed
hydra-billing/homs pull request #665
Opened 2022-07-12 12:18 UTC by StasShk

2022-07-13 08:39 UTC, TimAle requested changes

2022-07-13 08:39 UTC, TimAle commented on config/locales/bp/ru.new_customer.yml
>        homsOrderDataInstallDate: Дата подключения
It's actually confusing: for some types of fields yous should use `label`, for other types you shouldn't. Make it consistent, please.

2022-07-13 08:39 UTC, TimAle commented on hbw/app/javascript/packs/hbw/components/form/string.js.jsx
> +      const tooltip = this.context.translateBP(`${task.process_key}.${task.key}.${this.props.name}.message`,
it's "title", "tooltip" is already occupied by `this.tooltip`

2022-07-13 08:39 UTC, TimAle commented on spec/hbw/features/bp_form/translation_spec.rb
> +      expect(page).to have_content 'Field does not match regex'
p

2022-07-15 10:19 UTC, TimAle requested changes

2022-07-15 10:19 UTC, TimAle commented on CHANGELOG.md
> +- [#665](https://github.com/hydra-billing/homs/pull/665) Add tooltip message translation for string field
a dot at the end, please

2022-07-15 10:19 UTC, TimAle commented on CHANGELOG.md
>     fileUploadField: Field label
looks like you changed these two field types only, but it's not true

2022-07-15 10:19 UTC, TimAle commented on hbw/app/javascript/packs/hbw/components/form/string.js.jsx
> +        this.props.params.message || this.context.translate('errors.field_is_required'));
prefetch `name` and `params` from props at line 90 please, keep the style consistent

2022-07-15 12:48 UTC, StasShk commented
https://wiki.hydra-billing.ru/pages/viewpage.action?pageId=71368790

2022-07-18 11:03 UTC, TimAle requested changes

2022-07-18 11:03 UTC, TimAle commented on CHANGELOG.md
> +  String filed had additional key "message" for tooltip message, file_upload has input_text and browse_link_text keys.
```suggestion
- BP localization config structure was changed. Now input labels for the next field types should be placed in key "label": `checkbox`, `datetime`, `file_list`, `file_upload`, `select`, `select_table`, `string`, `submit_button` and `text`.
  `string` field has additional key "message" for tooltip message, `file_upload` has `input_text` and `browse_link_text` keys.
```

2022-07-19 07:51 UTC, TimAle approved these changes

2022-07-19 07:51 UTC, merged