HBW-392 Filter process instance by entity type
hydra-billing/homs pull request #687
Opened 2023-01-27 12:01 UTC by GideonEXE

2023-01-31 08:56 UTC, NatalieKor requested changes

2023-01-31 08:56 UTC, NatalieKor commented on spec/features/orders/orders_mock.yml
> +          id: "vacation_request:469:222222"
I guess it's 222223

2023-01-31 09:14 UTC, NatalieKor approved these changes

2023-01-31 11:17 UTC, TimAle requested changes

2023-01-31 11:17 UTC, TimAle commented on config/hbw.yml.sample
> +  use_bpm_stub: true
let's try without it

2023-01-31 13:21 UTC, TimAle requested changes

2023-02-01 09:34 UTC, TimAle approved these changes

2023-02-01 09:35 UTC, merged