HOMS-457 Update dependencies
hydra-billing/homs pull request #695
Opened 2023-04-18 20:55 UTC by StasShk

2023-05-12 09:04 UTC, GideonEXE requested changes

2023-05-12 09:04 UTC, GideonEXE commented on spec/javascript/helpers/setup_tests.js
> +global.window ??= window;
Why?

2023-05-15 12:55 UTC, flash-gordon commented on spec/javascript/helpers/setup_tests.js
> +global.window ??= window;
Or rather "Why??"

2023-05-16 07:58 UTC, GideonEXE approved these changes

2023-05-16 07:58 UTC, merged