HBW-398 Add services select table
hydra-billing/homs pull request #726
Opened 2023-10-04 07:43 UTC by EternalStuden1

2023-10-09 15:19 UTC, TimAle requested changes

2023-10-09 15:19 UTC, TimAle commented on hbw/app/models/hbw/fields/services_table.rb
> +      def currency_code
we will do it after introducing a lib for money formatting

2023-10-09 15:19 UTC, TimAle commented on hbw/app/javascript/packs/hbw/components/form/services_table.tsx
> +type HeaderEntity = {
or even `Columns`

2023-10-11 06:57 UTC, EternalStuden1 commented on hbw/app/javascript/packs/hbw/components/form/services_table.tsx
> +  }
There are 2 different options: hiddenHeaders form definition is set to [] and not set at all. In the first case we should show all headers, in the second case - hide default list of headers. That's why it's important to have undefined | string[]

2023-10-11 09:33 UTC, EternalStuden1 commented on hbw/app/javascript/packs/hbw/components/form/services_table.tsx
> +  allowProvisioning: number,
Value from db is fetched as constant (`CL_Creating_Allowed`/`CL_Creating_Forbidden`), thus it's type is number

2023-10-11 09:48 UTC, EternalStuden1 commented on hbw/app/javascript/packs/hbw/constants/c_l_creating_state.ts
> +// eslint-disable-next-line no-shadow
![Снимок экрана 2023-10-11 в 12 48 31](https://github.com/hydra-billing/homs/assets/51130595/07f0c89f-4467-47b7-954c-e7fd894fb6ab)

2023-10-13 15:06 UTC, TimAle requested changes

2023-10-16 08:13 UTC, EternalStuden1 commented on hbw/app/javascript/packs/hbw/components/form/services_table.tsx
> +      { isColumnVisible(columns, 'phone') && <td className="white-space-no-wrap">
No. Column with service address should not be whitespaced as its content wrap to the next line is acceptable

2023-10-16 09:54 UTC, TimAle commented on hbw/app/javascript/packs/hbw/components/form/services_table.tsx
> +      { isColumnVisible(columns, 'phone') && <td className="white-space-no-wrap">
but...
<img width="740" alt="image" src="https://github.com/hydra-billing/homs/assets/7077548/92bb957d-c99b-4ac3-a361-dace9bc30872">

2023-10-17 08:19 UTC, TimAle requested changes

2023-10-17 08:19 UTC, TimAle commented on hbw/app/models/hbw/fields/services_table.rb
> +          subscription['allowProvisioning'] = subscription['allowProvisioning'] == 1212
magic number

2023-10-19 07:51 UTC, TimAle approved these changes

2023-10-19 07:51 UTC, TimAle commented on hbw/app/models/hbw/fields/services_table.rb
> +        binding.pry
```suggestion

```

2023-10-19 08:08 UTC, merged